name: Build and test .NET app demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build & Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Build the project
      run: dotnet build

    - name: Run the tests
      run: dotnet test
      
